language: node_js
node_js:
    - '6.1'
matrix:
    allow_failures:
        - node_js: '0.11'

before_install:
    - npm install -g babel-cli
    - npm install -g mocha

before_script:
    - babel ./src/Swing.js --out-file ./dist/Swing.js

install:
    - npm install
notifications:
    email: false